---
title: "CSN LAB2"
author: "Fatima"
date: "2023-09-21"
output: html_document
---
```{r}
library(rstudioapi)
require("stats4") # for MLE
require("VGAM") # for the Riemann-zeta function
library(bbmle)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
setwd(dirname(getSourceEditorContext()$path))
```

#auxiliar functions

```{r}
sum_log_terms <- function(k) {
  if(k > 1) sum(log(2:k))
  else 0
}

get_C <- function(x){
      C <- c()
      for (k in x) {C <- c(C, sum_log_terms(k))}
      return (sum(C))
}

h_fct <- function(gamma, k_max) {
  out <- 0
  for (x in 1:k_max) {
    out <- out + x^(-gamma)
  }
  return(out)
}

```

# 1 Introduction

```{r cars}
#save all the data into a dataframe
data_dir <- "./in-degree_sequences/data/"
languages <- unlist(lapply(list.files(data_dir), function(x) gsub( "_in-degree_sequence.txt" , "", x)))

data <- data.frame(language = character(), degree_sequence = numeric())
for (f in list.files(data_dir)){
  degree_sequence <- read.table(paste0(data_dir, f),header = FALSE)$V1
  degree_sequence <- degree_sequence[degree_sequence != 0] #removing unconnected nodes
  lang <- gsub("_in-degree_sequence.txt" , "", f)
  data <- rbind(data, data.frame(language = lang, degree_sequence = degree_sequence))
}
```

```{r cars}
#TABLE 1 
table1 <- data.frame(Language = character(), 
                     N = numeric(),  
                     MaximumDegree = numeric(), 
                     degree = numeric(), 
                     M.N = numeric(), 
                     N.M = numeric())

for(lang in languages){
  degree_sequence <- as.data.frame(data[data$language == lang,]$degree_sequence)
  N <- dim(degree_sequence)[1]
  M <- sum(degree_sequence)
  dt_aux <- data.frame(
    Language = lang,
    N = N,
    MaximumDegree = max(degree_sequence),
    M.N = M/N,
    N.M = N/M
  )
  table1 <- rbind(table1, dt_aux)
}
```


#2 Visualization


```{r cars}
#normal scale
for(lang in languages){
  degree_sequence <- as.data.frame(data[data$language == lang,]$degree_sequence)
  degree_spectrum = table(degree_sequence)
  barplot(degree_spectrum, main = lang,
  xlab = "degree", ylab = "number of vertices")
}
```

```{r cars}
#log-log scale
for(lang in languages){
  barplot(degree_spectrum, main = lang,
  xlab = "degree", ylab = "number of vertices", log = "xy")
}
```

# 3 PARAMETERS ESTIMATION & MODEL SELECTION


## log likelihood functions

```{r}
minus_log_likelihood_zeta <- function(gamma) {
      gamma * sum(log(x)) + length(x) * log(zeta(gamma))
}

minus_log_likelihood_zeta_right_truncated <- function(gamma, k_max) {
      gamma * sum(log(x)) + length(x) * log(h_fct(gamma, k_max)) 
}

minus_log_likelihood_disp_poisson <- function(lambda){
      M <- sum(x)
      N <- length(x)
      e <- exp(1)
      C <- get_C(x)
      loglikelihood <- M*log(lambda) - N*(lambda + log(1-e^(-lambda))) - C
      return(-1*loglikelihood)
}

minus_log_likelihood_disp_geometric <- function(q){
  n <- length(x)
  -((sum(x) - n) * log(1 - q) + n * log(q))
}

get_AIC <- function(m2logL,K,N) { m2logL + 2*K*N/(N-K-1)}

```


## finding best parametrs values and AIC

```{r cars}
best_param_values <- function(x){
  
      params <- c()
      aics <- c()

      # -------------------- Displaced Poisson --------------------

      mle_disp_poisson <- mle(minus_log_likelihood_disp_poisson,
                      start = list(lambda = sum(x)/length(x)), method = "L-BFGS-B",  #M/N
                      lower = c(0.000001))

      val <- attributes(summary(mle_disp_poisson))$coef[1]
      aic <- get_AIC(attributes(summary(mle_disp_poisson))$m2logL, 1, N)
      params <- c(params, val)
      aics <- c(aics, aic)

      #------------ Displaced Geometric ---------------

      mle_disp_geometric <- mle(minus_log_likelihood_disp_geometric,
                                start=list(q = length(x)/sum(x))) #N/M

      val <- attributes(summary(mle_disp_geometric))$coef[1]
      aic <- get_AIC(attributes(summary(mle_disp_geometric))$m2logL, 1, N)
      params <- c(params, val)
      aics <- c(aics, aic)


      # -------------------- Zeta Dist. --------------------

      mle_zeta <- mle(minus_log_likelihood_zeta,
                start = list(gamma = 2), method = "L-BFGS-B", lower = c(1.0000001))

      val <- attributes(summary(mle_zeta))$coef[1]
      aic <- get_AIC(attributes(summary(mle_zeta))$m2logL, 1, N)
      params <- c(params, val)
      aics <- c(aics, aic)

      # -------------------- Zeta Dist. Gamma = 2 --------------------

      aic <- get_AIC(2*minus_log_likelihood_zeta(2), 1, N)
      aics <- c(aics, aic)
      
      # -------------------- Zeta Rigth Trucated --------------

      mle_zeta <- mle2(minus_log_likelihood_zeta_right_truncated,
                start = list(gamma = 2, k_max = length(x)), lower = c(gamma = 1.0001, k_max = max(x)), method = "L-BFGS-B")

      val1 <- attributes(summary(mle_zeta))$coef[1]
      val2 <- attributes(summary(mle_zeta))$coef[2]
      aic <- get_AIC(attributes(summary(mle_zeta))$m2logL, 1, N)
      params <- c(params, val1, val2)
      aics <- c(aics, aic)
  
      
      return(list(params, aics))
}

```

# TABLE 3 & TABLE 4

```{r}
table3 <- data.frame(
  Language = character(),
  `lambda` = numeric(), 
  `q` = numeric(),
  `gamma1` = numeric(),
  `gamma2` = numeric(),
  `k_max` = numeric()
  )

table4 <- data.frame(
  Language = character(),
  `AIC Poisson` = numeric(), 
  `AIC Dis.Geometric` = numeric(),
  `AIC Zeta` = numeric(),
  `AIC Zeta.Gamma=2` = numeric(),
  `AIC Zeta_rigth_truc` = numeric()
  )

i = 1
for(lang in languages){
  x <- data[data$language == lang,]$degree_sequence
  res <- best_param_values(x)
  table3[i,] <- c(lang, unlist(res[1]))
  res2 <- unlist(res[2]) - min(unlist(res[2])) #incremental AIC
  table4[i,] <- c(lang, res2)
  i <- i + 1
}

```


# 4 RESULTS

```{r}
table1 #Summary of the properties of the degree sequences
table3 #Summary of the most likely parameters
table4 #The AIC difference (∆) of a model on a given source.
```
# PLOTS

```{r}
# distribution functions
geometric.distribution <- function(k, q){
  return(q*(1-q)^(k-1))
}

poisson.distribution <- function(k, lambda){
  num <- lambda^k * exp(1)^(-lambda)
  den <- factorial(k)*(1 - exp(1)^(-lambda))
  return(num/den)
}

zeta.distribution <- function(k, gamma){
  num <- k^(-gamma)
  den <- zeta(gamma)
  return(num/den)
}

zeta.distribution.right.trucated <- function(k, gamma, k_max){
  num <- k^(-gamma)
  den <- h_fct(k_max, gamma)
  return(num/den)
}

```

```{r}
#for every language plot the frequency of each k and every distribution func.
for(lang in languages){
  n <- 50
  x <- data[data$language == lang,]$degree_sequence
  params <- table3[table3$Language == lang,]
  tab <- table(x)[1:n]
  seq <- seq(1:n)
  
  jpeg(paste0("./latex_files/plot_", lang, ".jpeg")) 

  # frequency plot
  barplot(tab, xlab = "k", ylab = "Frequency", main = paste(lang, "- Barplot & Probability Distribution"))
  
  #geometric.distribution line
  res <- unlist(lapply(seq, function(k) geometric.distribution(k = k, q = as.numeric(params$q))))
  lines(seq, res * max(table(x)), col = "yellow", type = "l", lwd = 2)
  #poisson.distribution line
  res <- unlist(lapply(seq, function(k) poisson.distribution(k = k, lambda = as.numeric(params$lambda))))
  lines(seq, res * max(table(x)), col = "purple", type = "l", lwd = 2)
  #zeta.distribution line
  res <- unlist(lapply(seq, function(k) zeta.distribution(k = k, gamma = as.numeric(params$gamma1))))
  lines(seq, res * max(table(x)), col = "skyblue", type = "l", lwd = 2)
  #zeta.distribution gamma = 2 line
  res <- unlist(lapply(seq, function(k) zeta.distribution(k = k, gamma = 2)))
  lines(seq, res * max(table(x)), col = "red", type = "l", lwd = 2)
  #zeta.distribution.right.trucated line
  res <- unlist(lapply(seq, function(k) zeta.distribution.right.trucated(k = k, gamma = as.numeric(params$gamma2), k_max = as.numeric(params$k_max))))
  lines(seq, res * max(table(x)), col = "green", type = "l", lwd = 2)
  
  legend_labels <- c("geometric.distribution", "poisson.distribution", "zeta.distribution", "zeta.distribution gamma=2", "zeta.distribution.right.trucated")
  legend("topright", legend = legend_labels, col = c("yellow", "purple", "skyblue", "red", "green"), lty = 2, bty = "n")
  
  dev.off()


}

```


# CHECKING METHODS

```{r}
#save all the data into a dataframe
data_dir <- "./samples_from_discrete_distributions/data/"
data_samples <- data.frame(file = character(), degree_sequence = numeric())
files <- unlist(lapply(list.files(data_dir), function(x) gsub( ".txt" , "", x)))
files <- unlist(lapply(files, function(x) gsub( "sample_of_" , "", x)))

for (f in list.files(data_dir)){
  degree_sequence <- read.table(paste0(data_dir, f),header = FALSE)$V1
  file <- gsub(".txt" , "", f)
  file <- gsub("sample_of_" , "", file)

  data_samples <- rbind(data_samples, data.frame(file = file, degree_sequence = degree_sequence))
}

table3_samples <- data.frame(
  file = character(),
  `lambda` = numeric(), 
  `q` = numeric(),
  `gamma1` = numeric(),
  `gamma2` = numeric(),
  `k_max` = numeric()
  )

table4_samples <- data.frame(
  file = character(),
  `AIC Poisson` = numeric(), 
  `AIC Dis.Geometric` = numeric(),
  `AIC Zeta` = numeric(),
  `AIC Zeta.Gamma=2` = numeric(),
  `AIC Zeta_rigth_truc` = numeric()
  )

i = 1
for(f in files){
  try({
      x <- data_samples[data_samples$file == f,]$degree_sequence
      res <- best_param_values(x)
      table3_samples[i,] <- c(f, unlist(res[1]))
      res2 <- unlist(res[2]) - min(unlist(res[2])) #incremental AIC
      table4_samples[i,] <- c(f, res2)
      i <- i + 1
  }
  )
}

table3_samples
table4_samples
```


# EXPORTING TABLES TO LATEX
```{r}
library(xtable)

round_table <- function(df){
  cols <- colnames(df)[-1]
  df[cols] <- lapply(df[cols], as.numeric)
  df[cols] <- lapply(df[cols], function(x) round(x, digits = 4))
  return(df)

}
table_latex <- xtable(round_table(table1))
print.xtable(table_latex, file = "./latex_files/table1.tex", include.rownames = FALSE)
table_latex <- xtable(round_table(table3))
print.xtable(table_latex, file = "./latex_files/table3.tex", include.rownames = FALSE)
table_latex <- xtable(round_table(table4))
print.xtable(table_latex, file = "./latex_files/table4.tex", include.rownames = FALSE)
table_latex <- xtable(round_table(table3_samples))
print.xtable(table_latex, file = "./latex_files/table3_samples.tex", include.rownames = FALSE)
table_latex <- xtable(round_table(table4_samples))
print.xtable(table_latex, file = "./latex_files/table4_samples.tex", include.rownames = FALSE)
```


